version: '3.8'

services:
  apache:
    build:
      context: ./docker/image/apache
    container_name: trilux_apache_server
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ${DOCUMENT_ROOT-./form}:/var/www/public
      - ${PHP_INI-./docker/config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./docker/config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./docker/logs/apache2}:/var/log/apache2
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: trilux_mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
     # - mysql_data:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./docker/logs/mysql}:/var/log/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: trilux_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpass
    depends_on:
      - mysql

volumes:
  mysql_data:
